[IMP]Migrando stock_analytic
TRESCLOUD/account-analytic pull request #20
Opened 2022-01-06 20:14 UTC by gatunosh

2022-01-25 20:30 UTC, stevTresCloud requested changes

2022-01-25 20:30 UTC, stevTresCloud commented on stock_analytic/__manifest__.py
> +# License LGPL-3.0 or later (http://www.gnu.org/licenses/agpl)
@gatunosh no se si sea buena idea quitar las organizaciones o personas que han ido colaborando en el módulo. Sería mejor añadir nuestro nombre, como lo están haciendo en v14
![image](https://user-images.githubusercontent.com/78817305/151050142-f226f075-f15e-47fe-9341-09ed74ede86b.png)

Hay que revisarle eso también en los otros dos módulos.

2022-01-25 20:30 UTC, stevTresCloud commented on stock_analytic/views/stock_move_views.xml
> +    </record>
@gatunosh falta la herencia a la vista search del stock.move. Se agrega los filtros para buscar por cuentas analíticas.

```suggestion
    </record>
    <record id="view_move_search_analytic" model="ir.ui.view">
            <field name="name">stock.move.search</field>
            <field name="model">stock.move</field>
            <field name="inherit_id" ref="stock.view_move_search" />
            <field name="arch" type="xml">
                <xpath expr="//field[@name='partner_id']" position="after">
                    <field
                        name="analytic_account_id"
                        groups="analytic.group_analytic_accounting"
                    />
                </xpath>
                <xpath
                    expr="//filter[@name='groupby_dest_location_id']"
                    position="after"
                >
                    <filter
                        string="Analytic Account"
                        name="analytic"
                        context="{'group_by':'analytic_account_id'}"
                        groups="analytic.group_analytic_accounting"
                    />
                </xpath>
            </field>
        </record>
```

2022-01-25 20:30 UTC, stevTresCloud commented on stock_inventory_analytic/models/res_company.py
> +# -*- coding: utf-8 -*-
@gatunosh igualmente hay comentarios de Copyright que creo no deberían quitarse. Revisale por favor eso también.

2022-01-25 20:30 UTC, stevTresCloud commented on stock_inventory_analytic/models/stock_quant.py
> +    )
@gatunosh revisale por favor si los tags se debería añadir. Entiendo que si porque prácticamente es una migración, y tomando como referencia que los otros dos módulos se maneja el campo de analytic_tag_ids, en este también se debería añadir el campo.

2022-01-25 21:24 UTC, gatunosh commented on stock_inventory_analytic/models/stock_quant.py
> +    )
No Andrés dijo que no

2022-01-25 22:40 UTC, stevTresCloud commented on stock_inventory_analytic/models/res_company.py
> +# -*- coding: utf-8 -*-
@gatunosh no hay que hacer esto... ya me dijo Andrés que no

2022-01-25 22:40 UTC, stevTresCloud commented on stock_analytic/__manifest__.py
> +# License LGPL-3.0 or later (http://www.gnu.org/licenses/agpl)
@gatunosh no hay que hacer esto... ya me dijo Andrés que no

2022-01-25 22:40 UTC, stevTresCloud commented on stock_analytic/views/stock_move_views.xml
> +    </record>
@gatunosh Esto es lo único para que le añadas por favor... y ya le fusiono... gracias

2022-01-26 15:58 UTC, stevTresCloud approved these changes

2022-01-26 15:58 UTC, merged